const fs = require('fs');
const path = require('path');
const basePath = path.resolve(__dirname, 'src');

function r(file, oldStr, newStr) {
  const fp = path.join(basePath, file);
  let c = fs.readFileSync(fp, 'utf8');
  const n = c.split(oldStr).length - 1;
  if (n === 0) { console.log(`  WARN: ${file} -> ${oldStr.substring(0,60)}`); return 0; }
  c = c.split(oldStr).join(newStr);
  fs.writeFileSync(fp, c, 'utf8');
  return n;
}
let t = 0;
function R(f, o, n) { t += r(f, o, n); }

// ========== CLIENT PROFILE PAGE ==========
const cp = 'features/clients/ClientProfilePage.tsx';
R(cp, ">Deactivate client</h2>", ">{t('clients.deactivateClient')}</h2>");
R(cp, '>Cancel\n', ">{t('common.cancel')}\n");
R(cp, "title=\"Edit\"", "title={t('common.edit')}");
R(cp, ">Edit\n", ">{t('common.edit')}\n");
R(cp, "title=\"Deactivate\"", "title={t('clients.deactivateClient')}");
R(cp, ">Deactivate\n", ">{t('common.deactivate')}\n");
R(cp, ">Log Communication\n", ">{t('clients.logCommunication')}\n");
R(cp, ">Total projects</p>", ">{t('clients.totalProjects')}</p>");
R(cp, ">Total budget</p>", ">{t('clients.totalBudget')}</p>");
Rcp = cp; // backup

// ========== EMPLOYEE DIRECTORY PAGE ==========
const ed = 'features/employees/EmployeeDirectoryPage.tsx';
R(ed, 'title="t(\'employees.noEmployeesFound\')"', "title={t('employees.noEmployeesFound')}");
R(ed, 'text="t(\'employees.tryDifferentSearch\')"', "text={t('employees.tryDifferentSearch')}");
R(ed, 'placeholder="Search name, email, employee id…"', "placeholder={t('employees.searchPlaceholder')}");
R(ed, '>All departments</option>', ">{t('attendance.allDepartments')}</option>");
R(ed, '>All skills</option>', ">{t('employees.allSkills')}</option>");
R(ed, '>All statuses</option>', ">{t('employees.allStatuses')}</option>");
R(ed, '>Active only</option>', ">{t('employees.activeOnly')}</option>");
R(ed, '>Inactive only</option>', ">{t('employees.inactiveOnly')}</option>");
R(ed, '>{total} {total === 1 ? ', ">{total} {total === 1 ? t('employees.employee') : t('employees.employees')");
// Fix the broken pattern for employee/employees count - it was split differently
R(ed, ">Employees</h1>", ">{t('employees.title')}</h1>");
R(ed, "t('employees.directoryOfEveryone')", "t('employees.directoryOfEveryone')");
R(ed, ">Add Employee", ">{t('employees.addEmployee')");
R(ed, ">Retry\n", ">{t('common.retry')}\n");
R(ed, "Active", "t('common.active')");
R(ed, "Inactive", "t('common.inactive')");
R(ed, ">Restore\n", ">{t('common.restore')}\n");
R(ed, ">Add Employee</h2>", ">{t('employees.addEmployee')}</h2>");
R(ed, ">Login email and password will be auto-generated.</p>", ">{t('employees.loginEmailAutoGenerated')}</p>");
R(ed, ">Full name *</span>", ">{t('employees.fullNameRequired')}</span>");
R(ed, ">Contact email (optional)</span>", ">{t('employees.contactEmailOptional')}</span>");
R(ed, ">Employee ID</span>", ">{t('employees.employeeId')}</span>");
R(ed, ">Designation</span>", ">{t('employees.designation')}</span>");
R(ed, ">Department</span>", ">{t('employees.department')}</span>");
R(ed, ">No department</option>", ">{t('employees.noDepartment')}</option>");
R(ed, ">Role</span>", ">{t('common.role')}</span>");
R(ed, ">Cancel\n", ">{t('common.cancel')}\n");
R(ed, ">Employee Created</h2>", ">{t('employees.employeeCreated')}</h2>");
R(ed, ">Share these credentials with", ">{t('employees.shareCredentialsWith')");
R(ed, ">Login Email</p>", ">{t('employees.loginEmail')}</p>");
R(ed, ">Password</p>", ">{t('common.password')}</p>");
R(ed, ">Done\n", ">{t('common.done')}\n");

// ========== EMPLOYEE PROFILE PAGE ==========
const ep = 'features/employees/EmployeeProfilePage.tsx';
R(ep, "t('employees.couldntLoadEmployee')", "t('employees.couldntLoadEmployee')");
R(ep, ">Overview</button>", ">{t('employees.overview')}</button>");
R(ep, ">Salary</button>", ">{t('employees.salary')}</button>");
R(ep, ">Documents</button>", ">{t('employees.documents')}</button>");
R(ep, "Professional</h2>", "t('employees.professional')");
R(ep, "t('employees.roleAndPosition')", "t('employees.roleAndPosition')");
R(ep, "Personal & Contact</h2>", "t('employees.personalAndContact')");
R(ep, ">Status</h2>", ">{t('employees.status')}</h2>");
R(ep, ">This month</h2>", ">{t('employees.thisMonth')}</h2>");
R(ep, ">Leave history</h2>", ">{t('leaves.leaveHistory')}</h2>");
R(ep, ">Salary Components</h2>", ">{t('employees.salaryComponents')}</h2>");
R(ep, ">Current package</h2>", ">{t('employees.currentPackage')}</h2>");
R(ep, ">Upload document</h2>", ">{t('employees.uploadDocument')}</h2>");
R(ep, ">Documents</h2>", ">{t('employees.documents')}</h2>");
R(ep, ">Employment and personal records.</p>", ">{t('employees.employmentAndPersonalRecords')}</p>");

// ========== FINANCE DASHBOARD ==========
const fd = 'features/finance/FinanceDashboardPage.tsx';
R(fd, ">Finance Dashboard</h1>", ">{t('finance.dashboard')}</h1>");
R(fd, "t('finance.revenueCollectionsExpenses') for {PERIOD_LABELS[period]}", "{t('finance.revenueFor', { period: t('finance.' + PERIOD_LABELS[period]) })}");
R(fd, ">Collections vs Expenses</h2>", ">{t('finance.collectionsVsExpenses')}</h2>");
R(fd, ">Across periods</p>", ">{t('finance.acrossPeriods')}</p>");
R(fd, ">Received\n", ">{t('common.received')}\n");
R(fd, ">Profit</h2>", ">{t('finance.profit')}</h2>");
R(fd, ">Invoice health</h2>", ">{t('finance.invoiceHealth')}</h2>");
R(fd, ">Invoices</span>", ">{t('finance.invoices')}</span>");
R(fd, ">Paid in full</span>", ">{t('finance.paidInFull')}</span>");
R(fd, ">Overdue</span>", ">{t('finance.overdue')}</span>");
R(fd, ">Approved expenses</span>", ">{t('finance.approvedExpenses')}</span>");

// ========== PROJECT DETAIL PAGE ==========
const pd = 'features/projects/ProjectDetailPage.tsx';
R(pd, "title=\"t('projects.projectNotFound')\"", "title={t('projects.projectNotFound')}");
R(pd, ">Edit project\n", ">{t('projects.editProject')}\n");
R(pd, "Deleting…", "t('common.deleting')");
R(pd, ">Delete project\n", ">{t('projects.deleteProject')}\n");
R(pd, ">Progress</p>", ">{t('projects.progress')}</p>");
R(pd, ">Studio fee</p>", ">{t('projects.studioFee')}</p>");
R(pd, ">Timeline</p>", ">{t('projects.timeline')}</p>");
R(pd, ">No team members yet.", ">{t('projects.noTeamMembersYet')}");
R(pd, ">Add team member\n", ">{t('projects.addTeamMember')}\n");
R(pd, ">Add phase\n", ">{t('projects.addPhase')}\n");

console.log(`\nTotal: ${t} replacements`);
